---
abstract: 'A searchable store backed by Elasticsearch'
author:
  - 'Nicolas Steenlant, C<< <nicolas.steenlant at ugent.be> >>'
build_requires:
  Module::Build: '0.3601'
  Test::More: '1.001003'
  Test::Simple: '1.001003'
configure_requires:
  Module::Build: '0.3601'
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.5, Dist::Zilla version 5.017, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Catmandu-Store-Elasticsearch
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  CQL::Parser: '1.12'
  Catmandu: '0.9206'
  Moo: '1.0'
  Search::Elasticsearch: '1.14'
  perl: v5.10.1
resources:
  bugtracker: https://github.com/LibreCat/Catmandu-Store-Elasticsearch/issues
  homepage: https://github.com/LibreCat/Catmandu-Store-Elasticsearch
  repository: https://github.com/LibreCat/Catmandu-Store-Elasticsearch.git
version: '0.01'
x_contributors:
  - 'Dave Sherohman <Dave.Sherohman@ub.lu.se>'
  - 'Patrick Hochstenbach <patrick.hochstenbach@ugent.be>'
  - 'Robin Sheat <robin@catalyst.net.nz>'
